/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CanvasesCanvasIdRouteImport } from './routes/canvases.$canvasId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CanvasesCanvasIdRoute = CanvasesCanvasIdRouteImport.update({
  id: '/canvases/$canvasId',
  path: '/canvases/$canvasId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/canvases/$canvasId': typeof CanvasesCanvasIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/canvases/$canvasId': typeof CanvasesCanvasIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/canvases/$canvasId': typeof CanvasesCanvasIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/canvases/$canvasId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/canvases/$canvasId'
  id: '__root__' | '/' | '/canvases/$canvasId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CanvasesCanvasIdRoute: typeof CanvasesCanvasIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canvases/$canvasId': {
      id: '/canvases/$canvasId'
      path: '/canvases/$canvasId'
      fullPath: '/canvases/$canvasId'
      preLoaderRoute: typeof CanvasesCanvasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CanvasesCanvasIdRoute: CanvasesCanvasIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
